name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        wget -O ibmcloud.tar.gz https://clis.cloud.ibm.com/download/bluemix-cli/1.1.0/linux64/archive
        tar xf ibmcloud.tar.gz 
        wget https://github.com/v2ray/v2ray-core/releases/download/v4.25.0/v2ray-linux-64.zip
        unzip v2ray-linux-64.zip -d v2ray_deploy/v2ray
        chmod 700 ./IBM_Cloud_CLI/ibmcloud ./IBM_Cloud_CLI/ibmcloud-analytics
        chmod 700 ./v2ray_deploy/v2ray/v2ray ./v2ray_deploy/v2ray/v2ctl
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME"

